# Generated by Django 4.2.7 on 2024-04-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=2)),
                ('games', models.CharField(max_length=2)),
                ('score', models.CharField(max_length=3)),
            ],
        ),
    ]
